apiVersion: v1
kind: DeploymentConfig
metadata:
  name: demo-angular-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: demo-angular-app-deployment
    spec:
      containers:
      - image: #{IMAGETAG}#
        name: demo-angular-app
        ports: 
        - containerPort: 80
